# リストの復習

In [5]:
# 変数によるデータ格納
A = 9
B = 6
C = 1
D = 4
E = 0
print(A, B, C, D, E)
# リストによるデータ格納
my_list = [9, 6, 1, 4, 0]
print(my_list)
# 例えばfor文ですべての変数に10をかけたい時

# 変数のデータ構造では以下の通り
ten = 10
A = 9 * ten
B = 6 * ten
C = 1 * ten
D = 4 * ten
E = 0 * ten
print(A, B, C, D, E)


# listのデータ構造では以下の通り
for i, tempalture in enumerate(my_list):
    my_list[i] = tempalture * 10

print(my_list)

# 例えばデータの数が100個とかになると、listを使ったほうが効率的

9 6 1 4 0
[9, 6, 1, 4, 0]
90 60 10 40 0
[90, 60, 10, 40, 0]


# Numpy配列の理解

In [19]:
import numpy as np

# 配列生成
x = np.array([1.0, 2.0, 3.0])
print(x)

# 算術演算
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
## 要素ごとの足し算
print(x + y)

## 引き算
print(x - y)
## 掛け算
print(x * y)
## 割り算
print(x / y)

# N次元配列
A = np.array([1.0, 2.0, 3.0])
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)  # 配列の形を出力
print(A.dtype)  # 配列内で使われているデータ型を出力

B = np.array([[3, 0], [0, 6]])
## 演算
print(A + B)
print(A - B)
print(A * B)


# ブロードキャスト
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A * B)

# 要素へのアクセス
X = np.array([[51, 52], [14, 19], [0, 4]])
print(X)
## 行にアクセス
for row in X:
    print(row)
## 不等号を用いたフィルタリング
## flattenを使った1次元配列化

[1. 2. 3.]
[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[[1 2]
 [3 4]]
(2, 2)
int64
[[ 4  2]
 [ 3 10]]
[[-2  2]
 [ 3 -2]]
[[ 3  0]
 [ 0 24]]
[[10 40]
 [30 80]]
[[51 52]
 [14 19]
 [ 0  4]]
[51 52]
[14 19]
[0 4]
